[project]
name = "maze_gen"
version = "0.1.0"
description = "A maze generation and pathfinding library implementing multiple algorithms (Prim's, Backtracking DFS, BFS)"
readme = "PACKAGE_README.md"
authors = [
    {name = "zboualam. slaaouin"}
]
keywords = ["maze", "algorithms", "pathfinding", "bfs", "dfs", "prims"]
requires-python = ">=3.10"
dependencies = []


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
